	title	TLS for Z80 by Konamiman
	subttl	Public constants for the TLS connection handler

    module TLS_CONNECTION

    module STATE

INITIAL: equ 0
HANDSHAKE: equ 1
ESTABLISHED: equ 2
LOCALLY_CLOSED: equ 3
REMOTELY_CLOSED: equ 4
FULL_CLOSED: equ 5

    endmod

    module ERROR_CODE

LOCAL_CLOSE: equ 1
ALERT_RECEIVED: equ 2
RECEIVED_RECORD_DECODE_ERROR: equ 3
CONNECTION_CLOSED_IN_HANDSHAKE: equ 4
UNEXPECTED_RECORD_TYPE_IN_HANDSHAKE: equ 5
UNEXPECTED_RECORD_TYPE_IN_ESTABLISHED: equ 6
UNEXPECTED_HANDSHAKE_TYPE_IN_HANDSHAKE: equ 7
UNEXPECTED_HANDSHAKE_TYPE_IN_ESTABLISHED: equ 8
SECOND_SERVER_HELLO_RECEIVED: equ 9
INVALID_SERVER_HELLO: equ 10
UNALLOWED_HANDSHAKE_TYPE_BEFORE_SERVER_HELLO: equ 11
FINISHED_BEFORE_CERTIFICATE: equ 12
BAD_FINISHED: equ 13
BAD_MAX_FRAGMENT_LEGTH: equ 14
INVALID_KEY_UPDATE: equ 15
UNSUPPORTED_SPLIT_HANDSHAKE_MESSAGE: equ 16
CONNECTION_CLOSED_IN_ESTABLISHED: equ 17

    endmod

    module ALERT_CODE

CLOSE_NOTIFY: equ 0
USER_CANCELED: equ 90
BAD_RECORD_MAC: equ 20
RECORD_OVERFLOW: equ 22
DECODE_ERROR: equ 50
DECRYPT_ERROR: equ 51
INTERNAL_ERROR: equ 80
UNEXPECTED_MESSAGE: equ 10
HANDSHAKE_FAILURE: equ 40
PROTOCOL_VERSION: equ 70
ILLEGAL_PARAMETER: equ 47

    endmod

    endmod
